settings:
  #################   DATASET CONFIG   ###################

  root_dir: "/content/main/data/visualsentiment/images"
  csv_file: "/content/main/data/visualsentiment/annotations.csv"
  task: "T2"
  
  #################   TRAINING CONFIG   ###################
  
  model_name: 'efficientnet_b3' #[vit_base_patch16_384]
  loss_fn: 'bce' #[ce | focal]

  # pretrained_backbone: ''                  # Pretrained backbone
  
  gpu_devices: '0'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 32
  num_workers: 2
  
  image_size: [384,384]               # should be square to prevent bugs [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
  keep_ratio: False                     # whether to use resize padding

  mixup: True

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "1cycle-yolo"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

  # gradient accumulation
  mixed_precision: False                # whether to use nvidia apex
  total_accumulate_steps: 0           # step * batch_size, not use if equal 0

  # Test time augmentation
  tta: False                             # whether to use TTA while validation
