settings:
  #################   DATASET CONFIG   ###################

  root_dir: "/content/main/data/devset_2021_Visual_Sentiment/images"
  train_csv: "/content/main/data/clean.csv"
  val_csv: "/content/main/data/testset_mediaeval.csv"
  task: "T1"
  
  #################   TRAINING CONFIG   ###################
  
  model_name: 'tf_efficientnet_b5_ns' #[vit_base_patch16_384]
  loss_fn: 'ce' #[ce | focal]

  # pretrained_backbone: ''                  # Pretrained backbone
  
  gpu_devices: '0'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 16
  num_workers: 2
  
  image_size: [300,300]               # should be square to prevent bugs [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
  keep_ratio: False                     # whether to use resize padding

  mixup: True

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

  # gradient accumulation
  mixed_precision: False                # whether to use nvidia apex
  total_accumulate_steps: 64           # step * batch_size, not use if equal 0

  # Test time augmentation
  tta: False                             # whether to use TTA while validation
